### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Review by xansec — CHANGES_REQUESTED** [review]
Please restore deleted workflows/dockerfiles. Please make the requested changes.

**Comment by rnshah9** [comment]
Latest run is failing due to a transient error; it should work when run again tomorrow.

**Review by xansec — APPROVED** [review]
Great,  LGTM!

**Comment by xansec** [comment]
Hmm, this seems to be failing. Can you take a look?
https://github.com/mayhemheroes/gambit

**Comment by rnshah9** [comment]
Weird, this wasn't failing locally. Opened another PR: #2

**Pull request merged**
